# Generated by Django 3.1.7 on 2021-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210226_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='ads', max_length=1500),
            preserve_default=False,
        ),
    ]
