# Generated by Django 3.1.7 on 2021-02-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
